import type { MenuItem } from './MenuItem';
import { getProductImage } from './ProductImages';

// Legacy WP base kept so individual items compile; overridden below.
const WP = 'https://berlioz.mx/wp-content/uploads';

// ═══════════════════════════════════════════════════════════
// BERLIOZ — CATÁLOGO OFICIAL (WooCommerce real)
// ═══════════════════════════════════════════════════════════

export const MENU_CATALOG: MenuItem[] = [
  // ── COFFEE BREAK — PAQUETES GRUPALES (precio fijo por grupo) ──
  {
    id: 'cb_am_cafe',
    name: 'Coffee Break AM - Café',
    description: 'Bocadillos salados, mini pan dulce, ensalada de frutas, yogurt orgánico con granola, café frío y snack. NO incluye café caliente.',
    pricePerPerson: 0,
    category: 'coffee_break',
    pricingModel: 'per_group',
    groupPrices: [
      { people: 4, price: 1440 },
      { people: 6, price: 1860 },
      { people: 8, price: 2700 },
      { people: 10, price: 3250 },
      { people: 15, price: 4390 },
    ],
    image: `${WP}/2025/08/coffeebreak_AM_cafe.jpg`,
    isTopSeller: true,
    agentNote: 'NO incluye café caliente. El café frío ya está incluido. Ofrecer Café/Té Berlioz como upgrade +$540.',
  },
  {
    id: 'cb_am_jugo',
    name: 'Coffee Break AM - Jugo',
    description: 'Bocadillos salados, mini pan dulce, ensalada de frutas, yogurt orgánico con granola, jugo natural y snack.',
    pricePerPerson: 0,
    category: 'coffee_break',
    pricingModel: 'per_group',
    groupPrices: [
      { people: 4, price: 1440 },
      { people: 6, price: 1860 },
      { people: 8, price: 2700 },
      { people: 10, price: 3250 },
      { people: 15, price: 4390 },
    ],
    image: `${WP}/2025/08/coffeebreak_AM_cafe2.jpg`,
  },
  {
    id: 'cb_pm',
    name: 'Coffee Break PM',
    description: 'Bocadillos salados, postres, churritos, crudités, agua de sabor.',
    pricePerPerson: 0,
    category: 'coffee_break',
    pricingModel: 'per_group',
    groupPrices: [
      { people: 4, price: 1240 },
      { people: 6, price: 1580 },
      { people: 8, price: 2340 },
      { people: 10, price: 2800 },
      { people: 15, price: 3650 },
    ],
    image: `${WP}/2025/08/coffeebreak_PM.jpg`,
    isTopSeller: true,
  },
  {
    id: 'cafe_te_berlioz',
    name: 'Café/Té Berlioz',
    description: 'Caja con café o agua para té + 12 vasos. Precio fijo, no escala por persona. Para 8-15 personas.',
    pricePerPerson: 540,
    category: 'coffee_break',
    pricingModel: 'fixed',
    image: `${WP}/2015/01/17.jpg`,
    agentNote: 'Precio FIJO $540 por unidad. NO escala por persona. Ofrecer como upgrade: "¿Quieres agregar café caliente? +$540"',
  },

  // ── SURTIDOS (precio fijo, para compartir) ──
  {
    id: 'surtido_camille',
    name: 'Surtido Camille',
    description: '15 bocadillos salados gourmet (5-7 personas)',
    pricePerPerson: 700,
    category: 'coffee_break_surtido',
    pricingModel: 'fixed',
    servesUpTo: 7,
    image: `${WP}/2023/03/Surtido-Camille-Berlioz-bocadillos.jpg`,
    isTopSeller: true,
  },
  {
    id: 'surtido_voltaire',
    name: 'Surtido Voltaire',
    description: '15 bocadillos salados gourmet (5-7 personas)',
    pricePerPerson: 750,
    category: 'coffee_break_surtido',
    pricingModel: 'fixed',
    servesUpTo: 7,
    image: `${WP}/2023/03/Surtido-Camille-Berlioz-bocadillos.jpg`,
  },
  {
    id: 'surtido_hugo',
    name: 'Surtido Hugo',
    description: '16 piezas pan dulce (6-8 personas)',
    pricePerPerson: 550,
    category: 'coffee_break_surtido',
    pricingModel: 'fixed',
    servesUpTo: 8,
    image: `${WP}/2025/06/WhatsApp-Image-2025-07-08-at-4.47.27-PM.jpg`,
  },
  {
    id: 'surtido_colette',
    name: 'Surtido Colette',
    description: '25 piezas pan dulce francés (5-7 personas)',
    pricePerPerson: 450,
    category: 'coffee_break_surtido',
    pricingModel: 'fixed',
    servesUpTo: 7,
    image: `${WP}/2018/03/berlioz_fabian-46-1-scaled.jpg`,
  },
  {
    id: 'surtido_balzac',
    name: 'Surtido Balzac',
    description: '25 pastelitos (7 personas)',
    pricePerPerson: 400,
    category: 'coffee_break_surtido',
    pricingModel: 'fixed',
    servesUpTo: 7,
    image: `${WP}/2024/02/pastelitos.jpg`,
  },
  {
    id: 'surtido_zadig',
    name: 'Surtido Zadig',
    description: '21 pastelitos (7 personas)',
    pricePerPerson: 400,
    category: 'coffee_break_surtido',
    pricingModel: 'fixed',
    servesUpTo: 7,
    image: `${WP}/2024/02/pastelitos.jpg`,
  },
  {
    id: 'surtido_snacks',
    name: 'Surtido de Snacks',
    description: 'Botana sana para compartir (6-8 personas)',
    pricePerPerson: 300,
    category: 'coffee_break_surtido',
    pricingModel: 'fixed',
    servesUpTo: 8,
    image: `${WP}/2018/03/Snacks-saludables-Berlioz-scaled.jpg`,
  },
  {
    id: 'surtido_dulces_mexicanos',
    name: 'Surtido Dulces Mexicanos',
    description: '51 piezas dulces mexicanos',
    pricePerPerson: 390,
    category: 'coffee_break_surtido',
    pricingModel: 'fixed',
    image: `${WP}/2026/03/Surtido-Dulces.jpg`,
  },
  // Mini surtidos
  {
    id: 'mini_surtido_hugo',
    name: 'Mini Surtido Hugo',
    description: '6 piezas mini pan dulce',
    pricePerPerson: 290,
    category: 'coffee_break_surtido',
    pricingModel: 'fixed',
    image: `${WP}/2025/06/Mini-danes.jpeg`,
  },
  {
    id: 'mini_surtido_colette',
    name: 'Mini Surtido Colette',
    description: '10 piezas mini pan dulce',
    pricePerPerson: 290,
    category: 'coffee_break_surtido',
    pricingModel: 'fixed',
    image: `${WP}/2024/02/Coffee-break.jpg`,
  },
  {
    id: 'mini_surtido_camille',
    name: 'Mini Surtido Camille',
    description: '6 mini bocadillos salados',
    pricePerPerson: 350,
    category: 'coffee_break_surtido',
    pricingModel: 'fixed',
    image: `${WP}/2025/06/MG_1600-scaled.jpg`,
  },
  {
    id: 'mini_surtido_voltaire',
    name: 'Mini Surtido Voltaire',
    description: '6 mini bocadillos salados',
    pricePerPerson: 350,
    category: 'coffee_break_surtido',
    pricingModel: 'fixed',
    image: `${WP}/2025/06/MG_1600-scaled.jpg`,
  },
  {
    id: 'mini_surtido_zadig',
    name: 'Mini Surtido Zadig',
    description: '8 mini postres',
    pricePerPerson: 240,
    category: 'coffee_break_surtido',
    pricingModel: 'fixed',
    image: `${WP}/2024/03/mini-balzac.jpg`,
  },
  {
    id: 'mini_surtido_balzac',
    name: 'Mini Surtido Balzac',
    description: 'Mini surtido postres',
    pricePerPerson: 220,
    category: 'coffee_break_surtido',
    pricingModel: 'fixed',
    image: `${WP}/2024/03/mini-balzac.jpg`,
  },

  // ── INDIVIDUALES COFFEE BREAK ──
  {
    id: 'ensalada_fruta',
    name: 'Ensalada de Fruta',
    description: 'Envase individual con cubierto y servilleta. Fruta de temporada.',
    pricePerPerson: 50,
    category: 'coffee_break_individual',
    pricingModel: 'per_person',
    image: `${WP}/2023/03/Desayuno-Berlioz-Coffee-break-ensalada-Frutas.jpg`,
  },
  {
    id: 'crudites',
    name: 'Crudités con Limón',
    description: 'Zanahoria y jícama. Envase individual.',
    pricePerPerson: 50,
    category: 'coffee_break_individual',
    pricingModel: 'per_person',
    image: `${WP}/2024/04/crudite.jpg`,
  },
  {
    id: 'yogurt_organico',
    name: 'Yogurt Orgánico',
    description: 'Con granola. Envase individual.',
    pricePerPerson: 50,
    category: 'coffee_break_individual',
    pricingModel: 'per_person',
    image: `${WP}/2020/03/berlioz_fabian-31.jpg`,
  },
  {
    id: 'pan_dulce_individual',
    name: 'Pan Dulce Individual',
    description: '2 mini panes. Envase individual.',
    pricePerPerson: 50,
    category: 'coffee_break_individual',
    pricingModel: 'per_person',
    image: `${WP}/2023/03/breakfast-ROMA-e1686675516812.jpg`,
  },
  {
    id: 'panque_naranja',
    name: 'Panqué de Naranja',
    description: 'Envase individual.',
    pricePerPerson: 50,
    category: 'coffee_break_individual',
    pricingModel: 'per_person',
    image: `${WP}/2023/03/Panque-de-naranja-Berlioz-zoom.jpg`,
  },
  {
    id: 'panque_pera',
    name: 'Panqué de Pera',
    description: 'Con trozos de chocolate. Envase individual.',
    pricePerPerson: 50,
    category: 'coffee_break_individual',
    pricingModel: 'per_person',
    image: `${WP}/2020/03/berlioz_fabian-21-scaled.jpg`,
  },
  {
    id: 'cookies',
    name: 'Cookies',
    description: 'Envase individual.',
    pricePerPerson: 50,
    category: 'coffee_break_individual',
    pricingModel: 'per_person',
    image: `${WP}/2023/02/Cookies-de-mantequilla-de-mani.jpg`,
  },
  {
    id: 'paleta_hielo',
    name: 'Paleta de Hielo',
    description: 'Paleta artesanal.',
    pricePerPerson: 45,
    category: 'coffee_break_individual',
    pricingModel: 'per_person',
    image: `${WP}/2026/03/WhatsApp-Image-2026-03-12-at-10.21.40-AM.jpg`,
  },
  {
    id: 'mix_semillas',
    name: 'Mix de Semillas',
    description: 'Naturales/romero/enchiladas/dulce-salado. Envase individual.',
    pricePerPerson: 60,
    category: 'coffee_break_individual',
    pricingModel: 'per_person',
    image: `${WP}/2020/03/berlioz_fabian-35-scaled-e1596130274963.jpg`,
  },
  {
    id: 'ensalada_pepino',
    name: 'Ensalada de Pepino',
    description: 'Envase individual.',
    pricePerPerson: 50,
    category: 'coffee_break_individual',
    pricingModel: 'per_person',
    image: `${WP}/2021/04/Ensalada-de-pepino-con-queso-de-cabra.jpg`,
  },
  {
    id: 'ensalada_jicama',
    name: 'Ensalada de Jícama',
    description: 'Envase individual.',
    pricePerPerson: 50,
    category: 'coffee_break_individual',
    pricingModel: 'per_person',
    image: `${WP}/2021/04/Ensalada-de-jicama-con-toronja.jpg`,
  },
  {
    id: 'snack_bag',
    name: 'Snack Bag',
    description: 'Bolsita individual de break.',
    pricePerPerson: 140,
    category: 'coffee_break_individual',
    pricingModel: 'per_person',
    image: `${WP}/2023/12/bag-snack.jpg`,
  },
  {
    id: 'snack_individual',
    name: 'Snack Individual',
    description: 'Garbanzos/churritos/cacahuates/chips/palomitas.',
    pricePerPerson: 50,
    category: 'coffee_break_individual',
    pricingModel: 'per_person',
    image: `${WP}/2018/03/Snacks-saludables-Berlioz-scaled.jpg`,
  },

  // ── DESAYUNO (precio por persona) ──
  {
    id: 'desayuno_berlioz',
    name: 'Desayuno Berlioz',
    description: 'Chilaquiles o enchiladas, fruta, pan dulce.',
    pricePerPerson: 170,
    category: 'desayuno',
    pricingModel: 'per_person',
    minQty: 20,
    agentNote: 'Mínimo 20 piezas iguales. Solo UNA opción de plato por día.',
    image: `${WP}/2024/11/comedorBERLIOZ.jpg`,
  },
  {
    id: 'box_chilaquiles_verdes_huevo',
    name: 'Box Chilaquiles Verdes - Huevo',
    description: 'Ensalada de frutas de temporada + chilaquiles verdes con huevo duro.',
    pricePerPerson: 310,
    category: 'desayuno',
    pricingModel: 'per_person',
    image: `${WP}/2023/04/Box-Chilaquiles-verdes-Berlioz-.jpg`,
    isTopSeller: true,
  },
  {
    id: 'box_chilaquiles_verdes_pollo',
    name: 'Box Chilaquiles Verdes - Pollo',
    description: 'Ensalada de frutas de temporada + chilaquiles verdes con pollo.',
    pricePerPerson: 330,
    category: 'desayuno',
    pricingModel: 'per_person',
    image: `${WP}/2023/04/Box-Chilaquiles-verdes-Berlioz-.jpg`,
  },
  {
    id: 'box_chilaquiles_rojos_huevo',
    name: 'Box Chilaquiles Rojos - Huevo',
    description: 'Ensalada de frutas de temporada + chilaquiles rojos con huevo duro.',
    pricePerPerson: 310,
    category: 'desayuno',
    pricingModel: 'per_person',
    image: `${WP}/2023/04/Box-Chilaquiles-verdes-Berlioz-.jpg`,
  },
  {
    id: 'box_chilaquiles_rojos_pollo',
    name: 'Box Chilaquiles Rojos - Pollo',
    description: 'Ensalada de frutas de temporada + chilaquiles rojos con pollo.',
    pricePerPerson: 330,
    category: 'desayuno',
    pricingModel: 'per_person',
    image: `${WP}/2023/04/Box-Chilaquiles-verdes-Berlioz-.jpg`,
  },
  {
    id: 'breakfast_roma',
    name: 'Breakfast in Roma',
    description: 'Croissant relleno de frittata con jamón de pavo.',
    pricePerPerson: 290,
    category: 'desayuno',
    pricingModel: 'per_person',
    variants: ['con yogurt', 'con pan dulce', 'con frittata sin croissant'],
    image: `${WP}/2023/03/berlioz_fabian-18-scaled-e1596123929266.jpg`,
    isTopSeller: true,
  },
  {
    id: 'breakfast_london',
    name: 'Breakfast London',
    description: 'Ciabatta con jamón de pierna ahumado.',
    pricePerPerson: 320,
    category: 'desayuno',
    pricingModel: 'per_person',
    variants: ['pierna y yogurt', 'pavo y yogurt', 'pierna y pan', 'pavo y pan'],
    image: `${WP}/2018/03/berlioz_fabian-46-1-scaled.jpg`,
  },
  {
    id: 'breakfast_montreal',
    name: 'Breakfast in Montreal',
    description: 'Salmón ahumado. PREMIUM.',
    pricePerPerson: 410,
    category: 'desayuno',
    pricingModel: 'per_person',
    variants: ['con yogurt', 'con pan recién horneado'],
    image: `${WP}/2023/03/Breakfast-in-Montreal-Berlioz1.jpg`,
  },
  {
    id: 'breakfast_madrid',
    name: 'Breakfast in Madrid',
    description: 'Desayuno estilo Madrid.',
    pricePerPerson: 300,
    category: 'desayuno',
    pricingModel: 'per_person',
    variants: ['jugo del día', 'yogurt', 'pan'],
    image: `${WP}/2023/03/berlioz_fabian-18-scaled-e1596123929266.jpg`,
  },
  {
    id: 'healthy_breakfast',
    name: 'Healthy Breakfast',
    description: 'Ensalada de jícama, chia pudding, granola con frutas.',
    pricePerPerson: 335,
    category: 'desayuno',
    pricingModel: 'per_person',
    image: `${WP}/2023/04/Healthy-breakfast-1.jpg`,
    isTopSeller: true,
  },
  {
    id: 'breakfast_blt',
    name: 'Breakfast BLT',
    description: 'Ciabatta con tocino/pavo.',
    pricePerPerson: 330,
    category: 'desayuno',
    pricingModel: 'per_person',
    variants: ['pavo y pan', 'pavo y yogurt', 'tocino y yogurt', 'tocino y pan'],
    image: `${WP}/2025/06/95A0102-1-scaled.jpg`,
  },
  {
    id: 'breakfast_bag_pavo',
    name: 'Breakfast Bag (Pavo)',
    description: 'Ciabatta de pavo para llevar.',
    pricePerPerson: 250,
    category: 'desayuno',
    pricingModel: 'per_person',
    image: `${WP}/2023/03/breakfast-bag.jpg`,
  },
  {
    id: 'breakfast_bag_especial',
    name: 'Breakfast Bag Especial',
    description: 'Sin ciabatta.',
    pricePerPerson: 280,
    category: 'desayuno',
    pricingModel: 'per_person',
    image: `${WP}/2023/03/Desayuno-Berlioz-Coffee-break-ensalada-Frutas.jpg`,
  },
  {
    id: 'breakfast_roma_vegetariano',
    name: 'Breakfast in Roma Vegetariano',
    description: 'Versión vegetariana del Breakfast in Roma.',
    pricePerPerson: 310,
    category: 'desayuno',
    pricingModel: 'per_person',
    image: `${WP}/2023/03/berlioz_fabian-18-scaled-e1596123929266.jpg`,
  },
  {
    id: 'breakfast_london_vegetariano',
    name: 'Breakfast London Vegetariano',
    description: 'Versión vegetariana del Breakfast London.',
    pricePerPerson: 340,
    category: 'desayuno',
    pricingModel: 'per_person',
    image: `${WP}/2018/03/berlioz_fabian-46-1-scaled.jpg`,
  },
  {
    id: 'breakfast_vegano',
    name: 'Breakfast Vegano',
    description: 'Desayuno 100% vegano.',
    pricePerPerson: 270,
    category: 'desayuno',
    pricingModel: 'per_person',
    image: `${WP}/2024/01/bag-2.jpg`,
  },

  // ── WORKING LUNCH — BOXES PREMIUM ──
  {
    id: 'salmon_box',
    name: 'Salmon Box',
    description: 'Salmón ahumado + ensalada César + cookies.',
    pricePerPerson: 410,
    category: 'working_lunch',
    pricingModel: 'per_person',
    image: `${WP}/2024/02/5.jpg`,
  },
  {
    id: 'pink_box',
    name: 'Pink Box',
    description: 'Pasta fría al pesto + pollo.',
    pricePerPerson: 370,
    category: 'working_lunch',
    pricingModel: 'per_person',
    variants: ['con papitas', 'con ensalada de jícama'],
    image: `${WP}/2023/03/cateringCorporativo12.jpg`,
    isTopSeller: true,
  },
  {
    id: 'black_box',
    name: 'Black Box',
    description: 'Ciabatta carnes frías + queso provolone.',
    pricePerPerson: 330,
    category: 'working_lunch',
    pricingModel: 'per_person',
    image: `${WP}/2018/03/berlioz_fabian-05-scaled.jpg`,
  },
  {
    id: 'golden_box',
    name: 'Golden Box',
    description: 'Ciabatta pollo marinado + queso fundido.',
    pricePerPerson: 330,
    category: 'working_lunch',
    pricingModel: 'per_person',
    image: `${WP}/2018/03/berlioz_fabian-05-scaled.jpg`,
  },
  {
    id: 'blt_box',
    name: 'BLT Box',
    description: 'Carpaccio de calabaza + ciabatta BLT.',
    pricePerPerson: 330,
    category: 'working_lunch',
    pricingModel: 'per_person',
    variants: ['con chips', 'con ensalada'],
    image: `${WP}/2023/03/95A0182-1-scaled.jpg`,
  },
  {
    id: 'aqua_box',
    name: 'Aqua Box',
    description: 'Carpaccio de calabaza + ciabatta.',
    pricePerPerson: 330,
    category: 'working_lunch',
    pricingModel: 'per_person',
    variants: ['con chips', 'con ensalada'],
    image: `${WP}/2025/08/aqua-box2.jpg`,
  },
  {
    id: 'st_tropez_box_pollo',
    name: 'St Tropez Box Pollo',
    description: 'Box St Tropez con pollo.',
    pricePerPerson: 330,
    category: 'working_lunch',
    pricingModel: 'per_person',
    image: `${WP}/2023/03/cateringCorporativo12.jpg`,
  },
  {
    id: 'st_tropez_box_veg',
    name: 'St Tropez Box Vegetariana',
    description: 'Box St Tropez vegetariana.',
    pricePerPerson: 350,
    category: 'working_lunch',
    pricingModel: 'per_person',
    image: `${WP}/2023/03/cateringCorporativo12.jpg`,
  },
  {
    id: 'box_mediterranea_pollo',
    name: 'Box Mediterránea Pollo',
    description: 'Box Mediterránea con pollo.',
    pricePerPerson: 320,
    category: 'working_lunch',
    pricingModel: 'per_person',
    image: `${WP}/2023/03/cateringCorporativo12.jpg`,
  },
  {
    id: 'box_mediterranea_veg',
    name: 'Box Mediterránea Vegetariana',
    description: 'Box Mediterránea vegetariana.',
    pricePerPerson: 280,
    category: 'working_lunch',
    pricingModel: 'per_person',
    image: `${WP}/2023/03/cateringCorporativo12.jpg`,
  },
  {
    id: 'box_tex_mex_pollo',
    name: 'Box Tex Mex Pollo',
    description: 'Box Tex Mex con pollo.',
    pricePerPerson: 310,
    category: 'working_lunch',
    pricingModel: 'per_person',
    image: `${WP}/2023/03/cateringCorporativo12.jpg`,
  },
  {
    id: 'box_tex_mex_vegana',
    name: 'Box Tex Mex Vegana',
    description: 'Box Tex Mex vegana.',
    pricePerPerson: 330,
    category: 'working_lunch',
    pricingModel: 'per_person',
    image: `${WP}/2023/03/cateringCorporativo12.jpg`,
  },
  {
    id: 'box_tex_mex_gf',
    name: 'Box Tex Mex Gluten Free',
    description: 'Box Tex Mex sin gluten.',
    pricePerPerson: 330,
    category: 'working_lunch',
    pricingModel: 'per_person',
    image: `${WP}/2023/03/cateringCorporativo12.jpg`,
  },
  {
    id: 'box_oriental',
    name: 'Box Oriental',
    description: 'Box Oriental.',
    pricePerPerson: 290,
    category: 'working_lunch',
    pricingModel: 'per_person',
    image: `${WP}/2025/02/IMG_8233-copia-1.jpg`,
  },
  {
    id: 'white_box',
    name: 'White Box',
    description: 'Ciabatta de milanesa de pollo.',
    pricePerPerson: 300,
    category: 'working_lunch',
    pricingModel: 'per_person',
    image: `${WP}/2023/03/white-box.jpg`,
  },
  {
    id: 'green_box',
    name: 'Green Box',
    description: 'Ensalada griega.',
    pricePerPerson: 340,
    category: 'working_lunch',
    pricingModel: 'per_person',
    image: `${WP}/2025/08/green-box3.jpg`,
  },
  {
    id: 'orzo_pasta_salad_box',
    name: 'Orzo Pasta Salad Box',
    description: 'Orzo pasta salad.',
    pricePerPerson: 390,
    category: 'working_lunch',
    pricingModel: 'per_person',
    image: `${WP}/2024/07/Orzo-Pollo.jpg`,
  },
  // Vegano/vegetariano WL
  {
    id: 'salad_box_pollo',
    name: 'Salad Box Pollo',
    description: 'Ensalada fría de pollo con agua fresca.',
    pricePerPerson: 280,
    category: 'working_lunch',
    pricingModel: 'per_person',
    variants: ['con agua del día', 'con postre en lugar de agua'],
    image: `${WP}/2019/04/Salad-box-pollo.jpg`,
  },
  {
    id: 'salad_box_vegetariana',
    name: 'Salad Box Vegetariana',
    description: 'Ensalada fría vegetariana.',
    pricePerPerson: 280,
    category: 'working_lunch',
    pricingModel: 'per_person',
    image: `${WP}/2019/04/Salad-box-pollo.jpg`,
  },
  {
    id: 'salad_box_vegana',
    name: 'Salad Box Vegana',
    description: 'Ensalada fría vegana.',
    pricePerPerson: 300,
    category: 'working_lunch',
    pricingModel: 'per_person',
    image: `${WP}/2019/04/Salad-box-pollo.jpg`,
  },
  {
    id: 'salad_box_pollo_gf',
    name: 'Salad Box Pollo Gluten Free',
    description: 'Ensalada fría de pollo sin gluten.',
    pricePerPerson: 280,
    category: 'working_lunch',
    pricingModel: 'per_person',
    image: `${WP}/2019/04/Salad-box-pollo.jpg`,
  },
  {
    id: 'pink_box_vegana',
    name: 'Pink Box Vegana',
    description: 'Pasta fría al pesto vegana.',
    pricePerPerson: 370,
    category: 'working_lunch',
    pricingModel: 'per_person',
    image: `${WP}/2023/10/web-03.jpg`,
  },
  {
    id: 'pink_box_keto',
    name: 'Pink Box Keto Sin Gluten',
    description: 'Pasta al pesto keto y sin gluten.',
    pricePerPerson: 370,
    category: 'working_lunch',
    pricingModel: 'per_person',
    image: `${WP}/2023/10/web-06.jpg`,
  },
  {
    id: 'pink_box_vegetariana',
    name: 'Pink Box Vegetariana',
    description: 'Pasta al pesto vegetariana.',
    pricePerPerson: 370,
    category: 'working_lunch',
    pricingModel: 'per_person',
    image: `${WP}/2024/10/web-_Mesa-de-trabajo-1.jpg`,
  },
  {
    id: 'orzo_vegetariana',
    name: 'Orzo Pasta Salad Box Vegetariana',
    description: 'Orzo pasta salad vegetariana.',
    pricePerPerson: 390,
    category: 'working_lunch',
    pricingModel: 'per_person',
    image: `${WP}/2024/07/Orzo-Pollo.jpg`,
  },
  {
    id: 'box_oriental_vegetariana',
    name: 'Box Oriental Vegetariana',
    description: 'Box Oriental vegetariana.',
    pricePerPerson: 290,
    category: 'working_lunch',
    pricingModel: 'per_person',
    image: `${WP}/2025/02/IMG_8233-copia-1.jpg`,
  },

  // ── WORKING LUNCH — ECONÓMICO ──
  {
    id: 'mini_box',
    name: 'Mini Box',
    description: 'Sandwich de pavo con panela.',
    pricePerPerson: 170,
    category: 'working_lunch_economico',
    pricingModel: 'per_person',
    image: `${WP}/2023/03/mini-BOX.webp`,
  },
  {
    id: 'box_economica_1',
    name: 'Box Económica 1 (Torta)',
    description: 'Torta económica.',
    pricePerPerson: 150,
    category: 'working_lunch_economico',
    pricingModel: 'per_person',
    minQty: 20,
    image: `${WP}/2020/04/Torta-berlioz.jpg`,
  },
  {
    id: 'box_economica_2',
    name: 'Box Económica 2',
    description: 'Quiche / pasta con pollo / torta jamón.',
    pricePerPerson: 170,
    category: 'working_lunch_economico',
    pricingModel: 'per_person',
    minQty: 20,
    image: `${WP}/2025/04/berlioz-product.jpg`,
  },
  {
    id: 'box_economica_3',
    name: 'Box Económica 3',
    description: 'Quiche / pasta con pollo.',
    pricePerPerson: 190,
    category: 'working_lunch_economico',
    pricingModel: 'per_person',
    minQty: 20,
    image: `${WP}/2025/04/berlioz-product.jpg`,
  },
  {
    id: 'comedor_berlioz',
    name: 'Comedor Berlioz',
    description: 'Arroz/frijoles/pasta + plato fuerte.',
    pricePerPerson: 170,
    category: 'working_lunch_economico',
    pricingModel: 'per_person',
    minQty: 20,
    agentNote: 'Mínimo 20 piezas iguales. Solo UNA opción por día.',
    image: `${WP}/2024/11/comedorBERLIOZ.jpg`,
  },
  {
    id: 'lunch_bag_pasta_pollo',
    name: 'Lunch Bag Pasta Pollo',
    description: 'Lunch bag con pasta de pollo.',
    pricePerPerson: 250,
    category: 'working_lunch_economico',
    pricingModel: 'per_person',
    image: `${WP}/2024/02/lunch-pasta.jpg`,
  },
  {
    id: 'lunch_bag_pasta_veg',
    name: 'Lunch Bag Pasta Vegetariana',
    description: 'Lunch bag con pasta vegetariana.',
    pricePerPerson: 270,
    category: 'working_lunch_economico',
    pricingModel: 'per_person',
    image: `${WP}/2024/02/lunch-pasta.jpg`,
  },
  {
    id: 'lunch_bag_ciabatta_pavo',
    name: 'Lunch Bag Ciabatta Pavo',
    description: 'Lunch bag con ciabatta de pavo.',
    pricePerPerson: 250,
    category: 'working_lunch_economico',
    pricingModel: 'per_person',
    image: `${WP}/2024/02/lunch-ciabatta.jpg`,
  },
  {
    id: 'lunch_bag_ciabatta_veg',
    name: 'Lunch Bag Ciabatta Vegetariana',
    description: 'Lunch bag con ciabatta vegetariana.',
    pricePerPerson: 270,
    category: 'working_lunch_economico',
    pricingModel: 'per_person',
    image: `${WP}/2018/03/berlioz_fabian-47-scaled.jpg`,
  },

  // ── TORTAS PIROPO ──
  {
    id: 'piropo_cochinita',
    name: 'Piropo Cochinita',
    description: 'Torta de cochinita + ensalada de jícama o pepino o papitas.',
    pricePerPerson: 280,
    category: 'tortas',
    pricingModel: 'per_person',
    image: `${WP}/2021/03/tortas_gourmet2.jpg`,
    isTopSeller: true,
  },
  {
    id: 'piropo_carnitas',
    name: 'Piropo Carnitas',
    description: 'Torta de carnitas.',
    pricePerPerson: 280,
    category: 'tortas',
    pricingModel: 'per_person',
    image: `${WP}/2021/03/tortas_gourmet2.jpg`,
  },
  {
    id: 'piropo_jamon',
    name: 'Piropo Jamón y Queso',
    description: 'Torta de jamón y queso.',
    pricePerPerson: 280,
    category: 'tortas',
    pricingModel: 'per_person',
    image: `${WP}/2021/03/tortas_gourmet2.jpg`,
  },
  {
    id: 'piropo_tinga',
    name: 'Piropo Tinga',
    description: 'Torta de tinga.',
    pricePerPerson: 280,
    category: 'tortas',
    pricingModel: 'per_person',
    image: `${WP}/2021/03/tortas_gourmet2.jpg`,
  },
  {
    id: 'piropo_camaron',
    name: 'Piropo Camarón',
    description: 'Torta de camarón (precio más alto por ingrediente).',
    pricePerPerson: 320,
    category: 'tortas',
    pricingModel: 'per_person',
    image: `${WP}/2021/03/tortas_gourmet2.jpg`,
  },
  {
    id: 'piropo_veggie',
    name: 'Piropo Veggie',
    description: 'Torta vegetariana.',
    pricePerPerson: 280,
    category: 'tortas',
    pricingModel: 'per_person',
    image: `${WP}/2021/03/tortas_gourmet2.jpg`,
  },
  {
    id: 'piropo_surtida',
    name: 'Piropo Surtida',
    description: 'Caja surtida de tortas.',
    pricePerPerson: 450,
    category: 'tortas',
    pricingModel: 'fixed',
    image: `${WP}/2021/03/piropo-surtida.jpg`,
  },

  // ── BEBIDAS ──
  {
    id: 'agua_bui_natural',
    name: 'Agua Bui Natural',
    description: '290ml.',
    pricePerPerson: 50,
    category: 'bebidas',
    pricingModel: 'per_person',
    image: `${WP}/2024/02/bui-natural.jpg`,
  },
  {
    id: 'agua_bui_mineral',
    name: 'Agua Bui Mineral',
    description: '290ml.',
    pricePerPerson: 50,
    category: 'bebidas',
    pricingModel: 'per_person',
    image: `${WP}/2024/02/bui-mineral.jpg`,
  },
  {
    id: 'agua_bui_infusionada',
    name: 'Agua Bui Infusionada',
    description: '290ml.',
    pricePerPerson: 50,
    category: 'bebidas',
    pricingModel: 'per_person',
    image: `${WP}/2024/02/bui-infusion.jpg`,
  },
  {
    id: 'agua_jamaica',
    name: 'Agua de Jamaica',
    description: '355ml.',
    pricePerPerson: 45,
    category: 'bebidas',
    pricingModel: 'per_person',
    image: `${WP}/2023/03/Aguas-de-sabor-Berlioz.jpg`,
  },
  {
    id: 'agua_limon_menta',
    name: 'Agua Fresca de Limón con Menta',
    description: '355ml.',
    pricePerPerson: 45,
    category: 'bebidas',
    pricingModel: 'per_person',
    image: `${WP}/2023/12/agua-melon.jpg`,
  },
  {
    id: 'agua_coco',
    name: 'Agua de Coco',
    description: '330ml.',
    pricePerPerson: 45,
    category: 'bebidas',
    pricingModel: 'per_person',
    image: `${WP}/2025/05/WhatsApp-Image-2025-08-18-at-3.38.43-PM.jpg`,
  },
  {
    id: 'agua_temporada',
    name: 'Agua de Temporada',
    description: '355ml. Sabores rotativos.',
    pricePerPerson: 45,
    category: 'bebidas',
    pricingModel: 'per_person',
    image: `${WP}/2015/10/Jugos-Berlioz1.jpg`,
  },
  {
    id: 'coca_cola',
    name: 'Coca Cola',
    description: 'Lata 355ml.',
    pricePerPerson: 45,
    category: 'bebidas',
    pricingModel: 'per_person',
    image: `${WP}/2024/02/coca.jpg`,
  },
  {
    id: 'coca_cola_light',
    name: 'Coca Cola Light',
    description: 'Lata 355ml.',
    pricePerPerson: 45,
    category: 'bebidas',
    pricingModel: 'per_person',
    image: `${WP}/2024/02/6.jpg`,
  },
  {
    id: 'refresco_lata',
    name: 'Refresco Lata',
    description: '355ml. Sprite/Fanta/Mundet.',
    pricePerPerson: 45,
    category: 'bebidas',
    pricingModel: 'per_person',
    image: `${WP}/2024/02/sprite.jpg`,
  },
  {
    id: 'sanpellegrino_aranciata',
    name: 'Sanpellegrino Aranciata Rossa',
    description: 'Lata premium.',
    pricePerPerson: 50,
    category: 'bebidas',
    pricingModel: 'per_person',
    image: `${WP}/2024/11/sanpellegrino-aranciata-rossa.jpg`,
  },
  {
    id: 'sanpellegrino_melograno',
    name: 'Sanpellegrino Melograno',
    description: 'Lata premium.',
    pricePerPerson: 50,
    category: 'bebidas',
    pricingModel: 'per_person',
    image: `${WP}/2024/11/arancia.webp`,
  },
  {
    id: 'jugo_naranja',
    name: 'Jugo de Naranja (JUS Orgánico)',
    description: 'Jugo orgánico.',
    pricePerPerson: 60,
    category: 'bebidas',
    pricingModel: 'per_person',
    image: `${WP}/2025/05/JUS.png`,
  },
  {
    id: 'cafe_frio',
    name: 'Café Frío',
    description: 'Latte orgánico de avena.',
    pricePerPerson: 60,
    category: 'bebidas',
    pricingModel: 'per_person',
    image: `${WP}/2025/08/WhatsApp-Image-2025-07-08-at-4.45.22-PM.jpg`,
  },
];

// ── Helpers ──

export function getTopSellers(): MenuItem[] {
  return MENU_CATALOG.filter((item) => item.isTopSeller);
}

export function getByCategory(category: MenuItem['category']): MenuItem[] {
  return MENU_CATALOG.filter((item) => item.category === category);
}

/**
 * Get the best group price for a given number of people.
 * Returns the tier that fits (equal or next higher), or the largest tier if people exceeds all.
 */
export function getGroupPrice(item: MenuItem, people: number): number {
  if (!item.groupPrices || item.groupPrices.length === 0) return item.pricePerPerson;
  const sorted = [...item.groupPrices].sort((a, b) => a.people - b.people);
  for (const tier of sorted) {
    if (people <= tier.people) return tier.price;
  }
  const largest = sorted[sorted.length - 1];
  const perPerson = largest.price / largest.people;
  return Math.round(perPerson * people);
}

/**
 * Get per-person price for display purposes.
 */
export function getDisplayPrice(item: MenuItem, people: number): number {
  if (item.pricingModel === 'fixed') return item.pricePerPerson;
  if (item.pricingModel === 'per_group') {
    return Math.round(getGroupPrice(item, people) / people);
  }
  return item.pricePerPerson;
}
