import type { MenuItem } from './MenuItem';

const CDN = 'https://res.cloudinary.com/dsr7tnfh6/image/upload/w_800,q_auto,f_auto';

export const MENU_CATALOG: MenuItem[] = [
  // ── TOP SELLERS ──
  {
    id: 'surtido_camille',
    name: 'Surtido Camille',
    description: 'Bocadillos gourmet variados para compartir',
    pricePerPerson: 700,
    category: 'surtidos',
    image: `${CDN}/Surtido-Camille-Berlioz-bocadillos_paaynm`,
    isTopSeller: true,
  },
  {
    id: 'box_chilaquiles',
    name: 'Box Chilaquiles Verdes',
    description: 'Chilaquiles verdes o rojos con pollo',
    pricePerPerson: 310,
    category: 'desayuno',
    image: `${CDN}/Box-Chilaquiles-verdes-Berlioz-_sycy3y`,
    isTopSeller: true,
  },
  {
    id: 'coffee_break_am',
    name: 'Coffee Break AM',
    description: 'Café, galletas y fruta fresca',
    pricePerPerson: 360,
    category: 'coffee_break',
    image: `${CDN}/coffeebreak_AM_cafe2_sda4yc`,
    isTopSeller: true,
  },
  {
    id: 'healthy_breakfast',
    name: 'Healthy Breakfast',
    description: 'Yogurt, granola, fruta y jugo natural',
    pricePerPerson: 335,
    category: 'desayuno',
    image: `${CDN}/Healthy-breakfast-2_mda5t1`,
    isTopSeller: true,
  },
  {
    id: 'torta_piropo',
    name: 'Torta Piropo',
    description: 'Torta gourmet con ingredientes artesanales',
    pricePerPerson: 280,
    category: 'tortas',
    image: `${CDN}/piropo-surtida_efarqs`,
    isTopSeller: true,
  },
  {
    id: 'breakfast_roma',
    name: 'Breakfast in Roma',
    description: 'Desayuno completo estilo Roma',
    pricePerPerson: 290,
    category: 'desayuno',
    image: `${CDN}/breakfast-ROMA-e1686675516812_bzzmzm`,
    isTopSeller: true,
  },
  // ── COFFEE BREAK ──
  {
    id: 'coffee_break_pm',
    name: 'Coffee Break PM',
    description: 'Café de la tarde con bocadillos dulces y salados',
    pricePerPerson: 360,
    category: 'coffee_break',
    image: `${CDN}/coffeebreak_PM_qlk47d`,
  },
  {
    id: 'coffee_break_general',
    name: 'Coffee Break Clásico',
    description: 'Café, té y galletas artesanales',
    pricePerPerson: 280,
    category: 'coffee_break',
    image: `${CDN}/Coffee-break_vxyazg`,
  },
  // ── DESAYUNO ──
  {
    id: 'breakfast_montreal',
    name: 'Breakfast in Montreal',
    description: 'Desayuno premium internacional',
    pricePerPerson: 410,
    category: 'desayuno',
    image: `${CDN}/Breakfast-in-Montreal-Berlioz1_msrqt6`,
  },
  {
    id: 'box_chilaquiles_pollo',
    name: 'Box Chilaquiles Pollo',
    description: 'Chilaquiles con pollo desmenuzado',
    pricePerPerson: 310,
    category: 'desayuno',
    image: `${CDN}/Box-Chilaquiles-pollo-Berlioz-_drfebk`,
  },
  {
    id: 'pan_dulce',
    name: 'Pan Dulce Individual',
    description: 'Selección de pan dulce artesanal',
    pricePerPerson: 95,
    category: 'desayuno',
    image: `${CDN}/Pan-dulce-Berlioz-desayuno-zoom_k4cqtv`,
  },
  {
    id: 'mini_danes',
    name: 'Mini Danés',
    description: 'Danés miniatura con rellenos variados',
    pricePerPerson: 85,
    category: 'desayuno',
    image: `${CDN}/Mini-danes_jxvrho`,
  },
  {
    id: 'panque_pera',
    name: 'Panqué de Pera con Chocolate',
    description: 'Panqué artesanal de pera y chocolate',
    pricePerPerson: 110,
    category: 'desayuno',
    image: `${CDN}/Panque-de-pera-con-chocolate-berlioz-zoom-1_qxvouv`,
  },
  {
    id: 'cookies_mani',
    name: 'Cookies de Mantequilla de Maní',
    description: 'Cookies artesanales crujientes',
    pricePerPerson: 75,
    category: 'desayuno',
    image: `${CDN}/Cookies-de-mantequilla-de-mani_zejgmc`,
  },
  // ── COMIDA ──
  {
    id: 'comedor_berlioz',
    name: 'Comedor Berlioz',
    description: 'Comida completa del día con ensalada',
    pricePerPerson: 170,
    category: 'comida',
    image: `${CDN}/comedorBERLIOZ_vvm0rz`,
  },
  {
    id: 'lunch_ciabatta',
    name: 'Lunch Ciabatta',
    description: 'Ciabatta gourmet con ingredientes frescos',
    pricePerPerson: 185,
    category: 'comida',
    image: `${CDN}/lunch-ciabatta_shrxzi`,
  },
  {
    id: 'lunch_pasta',
    name: 'Lunch Pasta',
    description: 'Pasta artesanal con salsa del día',
    pricePerPerson: 175,
    category: 'comida',
    image: `${CDN}/lunch-pasta_kakdco`,
  },
  {
    id: 'orzo_pollo',
    name: 'Orzo Pollo',
    description: 'Orzo con pollo y vegetales frescos',
    pricePerPerson: 180,
    category: 'comida',
    image: `${CDN}/Orzo-Pollo_esdfpp`,
  },
  {
    id: 'salad_box_pollo',
    name: 'Salad Box Pollo',
    description: 'Ensalada fresca con pollo a la plancha',
    pricePerPerson: 165,
    category: 'comida',
    image: `${CDN}/Salad-box-pollo_eqizjy`,
  },
  {
    id: 'pasta_pesto_pink',
    name: 'Pasta al Pesto Pink Box',
    description: 'Pasta al pesto en caja rosa premium',
    pricePerPerson: 190,
    category: 'comida',
    image: `${CDN}/Pasta-al-pesto-Pink-box-Berlioz-1_ijlkbj`,
  },
  // ── TORTAS GOURMET ──
  {
    id: 'torta_berlioz',
    name: 'Torta Berlioz',
    description: 'Torta signature de la casa',
    pricePerPerson: 280,
    category: 'tortas',
    image: `${CDN}/Torta-berlioz_hzjelx`,
  },
  {
    id: 'torta_gourmet',
    name: 'Torta Gourmet Surtida',
    description: 'Selección de tortas artesanales',
    pricePerPerson: 280,
    category: 'tortas',
    image: `${CDN}/tortas_gourmet2_devjfz`,
  },
  // ── SURTIDOS ──
  {
    id: 'surtido_colette',
    name: 'Surtido Colette',
    description: 'Mini pastelería francesa surtida',
    pricePerPerson: 65,
    category: 'surtidos',
    image: `${CDN}/mini-balzac_g5tbbm`,
  },
  {
    id: 'surtido_voltaire',
    name: 'Surtido Voltaire',
    description: 'Bocadillos gourmet premium',
    pricePerPerson: 107,
    category: 'surtidos',
    image: `${CDN}/pastelitos_pbbopa`,
  },
  {
    id: 'dulces_mexicanos',
    name: 'Surtido Dulces Mexicanos',
    description: 'Dulces típicos mexicanos surtidos',
    pricePerPerson: 80,
    category: 'surtidos',
    image: `${CDN}/Surtido-Dulces_nrm0yv`,
  },
  // ── BEBIDAS ──
  {
    id: 'jugos_berlioz',
    name: 'Jugos Berlioz',
    description: 'Jugos naturales del día',
    pricePerPerson: 65,
    category: 'bebidas',
    image: `${CDN}/Jugos-Berlioz1_pzchum`,
  },
  {
    id: 'agua_tamarindo',
    name: 'Agua de Tamarindo',
    description: 'Agua fresca natural de tamarindo',
    pricePerPerson: 50,
    category: 'bebidas',
    image: `${CDN}/agua-tamarindo_nbbxrc`,
  },
  {
    id: 'agua_melon',
    name: 'Agua de Melón',
    description: 'Agua fresca natural de melón',
    pricePerPerson: 50,
    category: 'bebidas',
    image: `${CDN}/agua-melon_ryvdkf`,
  },
  {
    id: 'cafe_servicio',
    name: 'Café y Té Continuo',
    description: 'Servicio de café y té ilimitado',
    pricePerPerson: 250,
    category: 'bebidas',
    image: `${CDN}/coffeebreak_AM_cafe_zhxb1e`,
  },
  {
    id: 'snack_bag',
    name: 'Snack Bag',
    description: 'Bolsa individual de snacks saludables',
    pricePerPerson: 140,
    category: 'bebidas',
    image: `${CDN}/bag-snack_zbsxe6`,
  },
  {
    id: 'snacks_saludables',
    name: 'Snacks Saludables',
    description: 'Selección de snacks saludables para compartir',
    pricePerPerson: 120,
    category: 'bebidas',
    image: `${CDN}/Snacks-saludables-Berlioz-scaled_pukfu4`,
  },
];

export function getTopSellers(): MenuItem[] {
  return MENU_CATALOG.filter((item) => item.isTopSeller);
}

export function getByCategory(category: MenuItem['category']): MenuItem[] {
  return MENU_CATALOG.filter((item) => item.category === category);
}
